publication:
  selection:
    filters:
      voter:
        tags:
          - [ "java" ]
          - [ "mobile" ]
      threshold:
        publishing: 0.7
        freeze: 0.25
  grow:
    strategy:
      machine:
        states:
          - bound: 50
            duration: "10s"
          - bound: 30
            duration: "30s"
          - bound: 10
            duration: "40s"
          - bound: 0
            duration: "60s"
    scheduler:
      delay: 3600
      threads: 5
  service:
    url: http://localhost:8090

server:
  servlet:
    context-path: /statistic

spring:
  jpa:
    open-in-view: false
  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/it_blog
    username: postgres # понятно что креды не надо так писать
    password: postgres # понятно что креды не надо так писать

logging:
  level:
    okhttp3: DEBUG
