spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: test_db

server:
  servlet:
    context-path: /publication-service