blog:
  generator:
    habr:
      subscriptions:
        - name: skyeng
          type: COMPANY
        - name: vk
          type: COMPANY


spring:
  jpa:
    open-in-view: false
  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/it_blog
    username: postgres # понятно что креды не надо так писать
    password: postgres # понятно что креды не надо так писать

logging:
  level:
    okhttp3: DEBUG
server:
  port: 8091