telegram:
  bots: # all registered bots
    - name: ItBlog # search in context by bot name (may be equal with !bean! name)
      token: ${it.blog.token.value} # registry have to produce methods aimed read placeholders from environment
      grabber:
        allowed_updates: [ MESSAGE, CALLBACK_QUERY, EDITED_CHANNEL_POST, CHANNEL_POST ]
      flows:
        - name: PublicationRecommendation
          start: onCommand
          command: /recommend
  flows:
    - name: PublicationRecommendation
      generation:
        type: sequential
        sequential: Start, Enter, Title, Description, End

ItBlog:
  editor: ${it.blog.editor}
  channel: ${it.blog.channel}

publication:
  service:
    url: http://localhost:8090

logging:
  level:
    com:
      github:
        ekgreen: DEBUG
spring:
  logging:
    hostDir: ${it.blog.bot.logs.host.dir}
