telegram:
  bots: # all registered bots
    - name: ItBlog # search in context by bot name (may be equal with !bean! name)
      token: ${it.blog.token.value} # registry have to produce methods aimed read placeholders from environment

spring:
  logging:
    hostDir: ${it.blog.bot.logs.host.dir}
